apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: authentication
  name: authentication
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: authentication
  type: LoadBalancer
status:
  loadBalancer: {}